#!/bin/bash

##############################################################################
# RaspAP 自動セットアップスクリプト (CLI only)
#   - wlan1 : 外部 Wi‑Fi クライアント (STA)
#   - wlan0 : アクセスポイント (172.16.0.0/24)
#   - DHCP  : 172.16.0.100‑200, GW/DNS = 172.16.0.254
#   - NAT   : wlan0 → wlan1
#   - RaspAP Web UI も有効 ( http://172.16.0.254 )
##############################################################################

# ========================= ユーザ設定 =======================================
SSID="Azazel-GW"          # アクセスポイント名
PSK="password"           # 8文字以上
AP_IP="172.16.0.254/24"  # wlan0 の固定 IP
DHCP_START="172.16.0.100"
DHCP_END="172.16.0.200"
COUNTRY="JP"              # Wi‑Fi 国コード
CHANNEL="6"              # 2.4 GHz の空き ch (1/6/11 推奨)
# ============================================================================

TOTAL=9        # ステップ総数（変更時は要更新）
STEP=0

start_step() {
  ((STEP++))
  echo -e "\n\e[1;33m[Step ${STEP}/${TOTAL}] $1 ...\e[0m"
}
end_step() {
  echo -e "\e[1;32m✔ Completed : $1\e[0m"
}
abort() {
  echo -e "\e[1;31m✖ Error at Step ${STEP}!   詳細を確認してください\e[0m" >&2
  exit 1
}
trap abort ERR

# ===== root 判定 =====
if [ "$(id -u)" -ne 0 ]; then
  echo "このスクリプトは sudo で実行してください" >&2
  exit 1
fi

set -euo pipefail

##############################################################################
start_step "システム更新 & 依存パッケージインストール"
##############################################################################
apt update && apt -y upgrade
apt install -y lighttpd php-cgi php-cli git hostapd dnsmasq iptables iptables-persistent netfilter-persistent
end_step "パッケージ"

##############################################################################
start_step "lighttpd + PHP FastCGI 有効化"
##############################################################################
lighty-enable-mod fastcgi-php || true
systemctl enable --now lighttpd
end_step "lighttpd"

##############################################################################
start_step "RaspAP を /opt/azazel へインストール"
##############################################################################
install -d /opt/azazel
[ -d /opt/azazel/raspap-webgui ] || git clone https://github.com/RaspAP/raspap-webgui.git /opt/azazel/raspap-webgui
bash /opt/azazel/raspap-webgui/installers/raspbian.sh --yes
end_step "RaspAP"

##############################################################################
start_step "RaspAP にインターフェースマッピングを設定"
##############################################################################
cat > /etc/raspap/networking/interfaces <<EOF
RASPI_WIFI_CLIENT_INTERFACE=wlan1
RASPI_WIFI_AP_INTERFACE=wlan0
EOF
end_step "インターフェースマッピング"

##############################################################################
start_step "wlan0 固定 IP を設定 (${AP_IP})"
##############################################################################
# 既存 Azazel ブロックを削除
sed -i '/^# --- Azazel wlan0 static ---/,$d' /etc/dhcpcd.conf || true
cat >> /etc/dhcpcd.conf <<EOF

# --- Azazel wlan0 static ---
interface wlan0
  static ip_address=${AP_IP}
  nohook wpa_supplicant
# ---------------------------
EOF
systemctl restart dhcpcd
end_step "wlan0 IP"

##############################################################################
start_step "dnsmasq で DHCP 範囲 (${DHCP_START}-${DHCP_END}) を設定"
##############################################################################
cat > /etc/dnsmasq.d/090_wlan0.conf <<EOF
# RaspAP wlan0 configuration (generated by script)
interface=wlan0
domain-needed
bogus-priv
dhcp-range=${DHCP_START},${DHCP_END},255.255.255.0,12h
dhcp-option=3,${AP_IP%/*}
dhcp-option=6,${AP_IP%/*}
EOF
systemctl restart dnsmasq
end_step "dnsmasq"

##############################################################################
start_step "hostapd を構成 (SSID=${SSID})"
##############################################################################
cat > /etc/hostapd/hostapd.conf <<EOF
driver=nl80211
ctrl_interface=/var/run/hostapd
ctrl_interface_group=0
interface=wlan0

ssid=${SSID}
country_code=${COUNTRY}
hw_mode=g
channel=${CHANNEL}
ieee80211n=1
wmm_enabled=1

wpa=2
wpa_passphrase=${PSK}
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
EOF
systemctl unmask hostapd
systemctl enable --now hostapd
end_step "hostapd"

##############################################################################
start_step "IP 転送と NAT を設定"
##############################################################################
cat > /etc/sysctl.d/90-azazel-ipforward.conf <<EOF
net.ipv4.ip_forward=1
EOF
sysctl -p /etc/sysctl.d/90-azazel-ipforward.conf
iptables -t nat -C POSTROUTING -s 172.16.0.0/24 -o wlan1 -j MASQUERADE 2>/dev/null || \
iptables -t nat -A POSTROUTING -s 172.16.0.0/24 -o wlan1 -j MASQUERADE
iptables-save > /etc/iptables/rules.v4
systemctl enable netfilter-persistent
end_step "NAT"

##############################################################################
start_step "サービス自動起動を確認"
##############################################################################
systemctl enable hostapd dnsmasq dhcpcd
# Web UI を使わない場合↓を無効化: systemctl disable raspapd
end_step "enable services"

##############################################################################
start_step "セットアップ完了"
##############################################################################
cat <<EOM
\n✔ すべてのステップが完了しました！\n---------------------------------------
内部AP        : SSID=${SSID} / PASS=${PSK}
内部ネット    : 172.16.0.0/24 (GW ${AP_IP%/*})
RaspAP UI     : http://${AP_IP%/*}  (admin / secret)
---------------------------------------\n今すぐ再起動すると設定が有効になります:\n  sudo reboot\n---------------------------------------
EOM
end_step "finish"
